### ISSUE TITLE
certain special character combonations not allowed

### ISSUE THREAD

**Issue by ItsRogueRen** [MrGlockenspiel/activate-linux#87]
So when trying to set this up as a joke for a friend, I found out that certain character combinations will try to do things like run a bash event (ex. I use Pop!_OS, but tring to run `activate-linux "Activate Pop!_OS" "Go to Settings to activate Pop!_OS"` would try to run `!_OS` as a bash event)

Is there any way to make it so that these things are ignored when running this?

**Comment by ReperakDev** [comment]
> [...] this is just a limitation of bash [...]
That's intended behavior. It's common to use double quotes for formatting (e.g. `FOOBAR="${foo}${bar}"), or, in this case, interpreting !_OS as an event.

**Comment by LizAinslie** [comment]
Yeah, I am aware that this is intended. My usage of such nomenclature was simply because it *does* limit people from using a raw `!` in double-quoted strings. The reason I wrote my comment, however, was because this is not something this project can (or needs to) fix, simply a side effect of using bash :P

**Comment by Ruby-Dragon** [comment]
This should be closed

**Comment by MrGlockenspiel** [comment]
Right as I was doing it lmao
